### ISSUE TITLE
Multiple source directories?

### ISSUE THREAD

**Issue by bendulum** [ianmcnally/plato-es6-demo#1]
How can this task be adapted to work with multiple source folders?
So basically in this line: `metrics:compile_source": "./node_modules/.bin/babel --optional runtime src/ --out-dir dist/metrics/src` I want to specify multiple directories instead of the single  `src/`.
Thanks for your help.

EDIT: Compiling the entire root directory and filtering the needed directories later seems overly expensive, considering the root directory also includes a ton of node modules...

**Comment by ianmcnally** [comment]
Hey @bendulum, check out https://babeljs.io/docs/usage/cli/ for more information on how to compile multiple directories. 

Regarding `node_modules` inside `src`, that's more of a project specific thing. In this project, `node_modules` would be outside `src`, at the root level. You're right that it'd be quite expensive (and unnecessary) to run dependencies through babel. I'd recommend setting up your project so `node_modules` is outside of your source code (e.g., `src/`).

**Comment by bendulum** [comment]
@imcnally Let me clarify, this is the structure of my project:

```
/
/components
/node_modules
/server
/scripts
...
```

I want to compile `components` and `server` directories. So providing root as `src` would include `node_modules` etc.
I have already looked at the babel-cli docs and done some googling but there is no mention on how to specify multiple directories as params in `babel src --out-dir lib`.

**Comment by ianmcnally** [comment]
You have a couple options:
1. You can run the babel task twice, if nothing else works. Gonna close this since it's not related to the project.
2. Move components, server, scripts into a new `src/`.

Thanks for dropping in! Always happy to see someone using a project.

**Comment by bendulum** [comment]
For what it's worth I have a gulp task now for that, pretty basic stuff.

```
var path = require('path');
var exec = require('child_process').exec;
var async = require('async');

var metrics = function() {
    var commands = [
        {
            dir: 'node_modules/.bin/',
            exe: 'babel',
            arg: '--optional runtime components/ --out-dir metrics/src/components'
        },
        {
            dir: 'node_modules/.bin/',
            exe: 'babel',
            arg: '--optional runtime scripts/ --out-dir metrics/src/scripts'
        },
        {
            dir: 'node_modules/.bin/',
            exe: 'babel',
            arg: '--optional runtime server/ --out-dir metrics/src/server'
        },
        {
            dir: 'node_modules/.bin/',
            exe: 'plato',
            arg: '-r -l ./node_modules/plato/.jshintrc -d metrics/report metrics/src'
        }
    ];
    async.map(
        commands,
        function(def, cb) {
            var exe = path.resolve(__dirname, def.dir, def.exe);
            var command = exe + ' ' + def.arg;
            exec(command, cb);
        },
        process.exit.bind(null, 0)
    );
};
```
